* SPES: Starship Programming Edutainment System

SPES is a 2D space combat Python programming game which is fun for both novice and
experienced coders!

You will control your starship by executing Python code.

There are two different frontends:
- command line
- built-in editor

* Running the Game

** Command Line Frontend

Navigate to the game directory:

#+BEGIN_SRC shell
cd path/to/spes_dir
#+END_SRC

Load the command line frontend and enter the interactive Python interpreter:

#+BEGIN_SRC
python -i spes_cmd.py
#+END_SRC

Start the game GUI running:

#+BEGIN_SRC python :classname example
gui.start()
#+END_SRC

** Built-in Editor Frontend

Just run the file spes_builtin.py:

#+BEGIN_SRC shell
python spes_builtin.py
#+END_SRC

* How to Play

Try these commands to begin with:

#+BEGIN_SRC python :classname example
# move player's ship at 45 degree direction for distance of 200 units
p.move(45, 200)

# fire missile or laser in 45 degree direction
p.missile(45)
p.laser(45)

# p is shorthand for PLAYER - this will display a printed representation of the Python object 'p'
p

# show help for the object 'p'
help(p)

# show help for the player's 'move' function
help(p.move)
#+END_SRC

NOTE: all commands must be given in valid Python 3 syntax - so brackets are
required around all function arguments.

* Credits

Game concept and all code by B. S. Chambers.

Email: ben@bschambers.info

Website: https://github.com/bschambers/spes

* License

Copyright 2019-present B. S. Chambers.

Distributed under GPL, version 3.
